########################################################
# Turn Bar lights Off if no motion is detected last 3 minutes
########################################################
alias: Bar Lights Last Tripped
########################################################
# Check every 2 minutes
########################################################
trigger:
  platform: time
  minutes: '/5'
  seconds: 00
condition:
 condition: and
 conditions:
########################################################
# Check Bar Lights on for 1 minute. Manual on Fix
########################################################
  - condition: state
    entity_id: light.bar_counter_light
    state: 'on'
    for: 00:01:00

########################################################
# Check Guest Mode is Off
########################################################
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
########################################################
# Check since last tripped, if more than 2.5 minutes True
# Time in seconds
########################################################
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.ecolink_pir_bar_area_motion_sensor_14_0.last_changed) > 150}}'
action:
  - service: light.turn_off
    entity_id: light.bar_counter_light
