#Check kitchen lights status every hour and trigger timeout.
#Just in case if no motion was triggered after HA restart
alias: Check kitchen lights every hour
trigger:
   platform: time
   minutes: '/55'
   seconds: 00

condition:
 condition: and
 conditions:

  - condition: state
    entity_id: group.kitchen_lights
    state: 'on'
  - condition: state
    entity_id: script.kitchen_lights_timeout
    state: 'off'

action:
   - service: homeassistant.turn_on
     entity_id: script.kitchen_lights_set_timeout
