########################################################
# Force Close garage on GCM notification button
########################################################
alias: GCM force close garage
trigger:
  platform: event
  event_type: html5_notification.clicked
  event_data:
    action: close_garage

condition:
 condition: and
 conditions:
########################################################
# Garage door is open
########################################################
  - condition: state
    entity_id: binary_sensor.garage_door_sensor_1
    state: 'on'
  #######################################################
  # Close garage
  #######################################################
action:
  - service: script.turn_off
    entity_id: script.garage_close_main
  - service: script.turn_on
    entity_id: script.garage_click

  #######################################################
  # GCM notify garage closed time
  #######################################################
  # 
  # - service: notify.push_gcm
  #   data_template:
  #     title: "Garage Door"
  #     message:  "The garage was closed at - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p') }}"
