alias: Laundry room Lights Auto On
trigger:
  platform: state
  entity_id: binary_sensor.laundry_room_door
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.laundry_room
      state: 'off'
    # - condition: numeric_state
      # entity_id: sun.sun
      # value_template: '{{ state.attributes.elevation }}'
      # below: 1.5
action:
  - service: switch.turn_on
    entity_id: switch.laundry_room
  - delay: 00:10:00
  - service: switch.turn_off
    entity_id: switch.laundry_room