########################################################
# Double check Laundry Light Status and Compare with
# Laundry room door last tripped and motion in the 
# Kitchen Area last tripped.
########################################################
alias: Laundry Room Light Check Last Tripped
########################################################
# Check every 20 minutes
########################################################
trigger:
  platform: time
  minutes: '/20'
  seconds: 00
condition:
 condition: and
 conditions:
########################################################
# Check Laundry Room Lights are On for at least 2 minutes
########################################################
  - condition: state
    entity_id: switch.laundry_room
    state: 'on'
    for: 00:02:00
    
########################################################
# Check Guest Mode is Off
########################################################
  # - condition: state
    # entity_id: input_boolean.guest_mode
    # state: 'off'
########################################################
# Check since last tripped, if more than X minutes True
# Time in seconds
# Check laundry room door sensor last tripped 10 minutes
# Check kitchen center PIR motion sensor last tripped  10 minutes
########################################################
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.laundry_room_door.attributes.last_tripped_time) > 600}}'
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.kitchen_sensor_motion.attributes.last_tripped_time) > 600}}'


action:
  service: switch.turn_off
  entity_id: switch.laundry_room