alias: Minimote 20 Button 1 Short Press Master Light On
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: aeotec_dsa03202_minimote_20
    scene_id: 1
action:
  service: switch.turn_on
  entity_id: switch.master_light
