alias: Minimote Button 1 Sprinkler Front Lawn 1 On
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: aeotec_dsa03202_minimote_11
    scene_id: 3
action:
  service: ifttt.trigger
  data: {"event":"skydrop_sprinkler_on", "value1":"2"}
