alias: Minimote 20 Button 3 Short Press Master Bath Light On
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: aeotec_dsa03202_minimote_20
    scene_id: 5
action:
  service: switch.turn_on
  entity_id: switch.master_bath
