########################################################
# Turn Patio Speakers On - Motion
# Don't turn on during wee hours and early morning
########################################################
alias: Patio Speakers Auto On
########################################################
trigger:
  platform: state
  entity_id: binary_sensor.patio_motion_sensor
  to: 'on'
condition:
 condition: and
 conditions:
  - condition: time
    before: '23:00:00'
    after: '09:00:00'
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.yamaha_receiver_zone_2
      state: 'on'
    - condition: state
      entity_id: media_player.yamaha_receiver_zone_2
      state: 'playing'

########################################################
# Turn on Patio Speakers
########################################################
action:
  - service: switch.turn_on
    entity_id: switch.patio_speakers
