###################################################################################################################
## Hide keep_alive switch
###################################################################################################################
homeassistant:
  customize:
    input_boolean.keep_alive:
      hidden: true

input_boolean:
  keep_alive:
    name: Dummy Switch
    initial: on

binary_sensor:
  - platform: mqtt
    state_topic: "/esp-master-bath/Master Bath/Motion"
    name: "Master Bath ESP Motion"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    device_class: motion
  - platform: template
    sensors:
###################################################################################################################
## Humidity differnce compared to family room
###################################################################################################################
      master_bath_below_threshold:
        friendly_name: "Master Bath Humidity Below Threshold"
        value_template: >-
          {{ (states.sensor.master_bath_humidity_difference.state | int) < (states.input_number.master_bath_humidity_threshold.state | int) }}
###################################################################################################################
## Motion senor last changed is more than timeout
###################################################################################################################
      master_bath_timeout_threshold:
        friendly_name: "Master Bath Timeout Threshold"
        entity_id: input_boolean.keep_alive
        value_template: >-
          {{ ((as_timestamp(now()) |int - (as_timestamp(states.binary_sensor.master_bath_esp_motion.last_changed) | int) | int ) /60) | int > (states.input_number.master_bath_timeout.state | int) }}

sensor:
    - platform: mqtt
      name: "Master Bath Temperature"
      state_topic: "/esp-master-bath/Master Bath/Temperature"
      qos: 0
      unit_of_measurement: "°F"
    - platform: mqtt
      name: "Master Bath Humidity"
      state_topic: "/esp-master-bath/Master Bath/Humidity"
      qos: 0
      unit_of_measurement: "%"
    - platform: mqtt
      name: "Master Bath Lux"
      state_topic: "/esp-master-bath/Master Bath/Lux"
      qos: 0
      unit_of_measurement: "Lux"
    - platform: template
      sensors:
        master_bath_humidity_difference:
          friendly_name: "Master Bath Humidity Difference"
          value_template: "{{ (states.sensor.master_bath_humidity.state | int) - (states.sensor.family_room_thermostat_humidity.state | int) }}"
    - platform: mqtt
      state_topic: "masterbath/humidity"
      name: "Master Bath Humidity Restore"
      value_template: "{{ value }}"
      qos: 1
    - platform: mqtt
      state_topic: "masterbath/timeout"
      name: "Master Bath Timeout Restore"
      value_template: "{{ value }}"
      qos: 1


###################################################################################################################
## Humidity & Timeout Thresholds
###################################################################################################################

input_number:
  master_bath_humidity_threshold:
    name: Master Bath Humidity Threshold
    initial: 20
    min: 0
    max: 100
    step: 1
  master_bath_timeout:
    name: Master Bath Time Out
    initial: 5
    min: 5
    max: 60
    step: 1

automation:

###################################################################################################################
## Publish Humidity Threshold Value upon input change
###################################################################################################################

  - alias: Master Bath Humidity MQTT
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_number.master_bath_humidity_threshold
    action:
      - service: mqtt.publish
        data_template:
          topic: "masterbath/humidity"
          retain: true
          payload: '{{ states.input_number.master_bath_humidity_threshold.state }}'

###################################################################################################################
## Publish Timeout Value upon input change
###################################################################################################################

  - alias: Master Bath Timeout MQTT
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_number.master_bath_timeout
    action:
      - service: mqtt.publish
        data_template:
          topic: "masterbath/timeout"
          retain: true
          payload: '{{ states.input_number.master_bath_timeout.state }}'

###################################################################################################################
## Restore Threshold Values from MQTT
###################################################################################################################

  - alias: Master Bath Restore Settings on Startup
    initial_state: true
    hide_entity: true
    trigger:
      platform: homeassistant
      event: start
    action:
      - delay:
          seconds: 5
      - service: input_number.set_value
        data_template:
          entity_id: input_number.master_bath_humidity_threshold
          value: "{{states.sensor.master_bath_humidity_restore.state}}"
      - service: input_number.set_value
        data_template:
          entity_id: input_number.master_bath_timeout
          value: "{{states.sensor.master_bath_timeout_restore.state}}"



###################################################################################################################
## Master bath auto turn on motion if KM Group is home ###
###################################################################################################################
  - alias: Master Bath Lights Motion ON
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bath_esp_motion
        to: 'on'

    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: group.km_status
        state: 'home'

    action:
      service: switch.turn_on
      entity_id: switch.master_bath_68

###################################################################################################################
## Master bath turn off if Humidity Differential is Below Set Amount and No Motion for Set minutes
###################################################################################################################

  - alias: Master Bath Humidity Level Low Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bath_below_threshold
        to: 'on'
    action:
      - wait_template: >-
          {{ states.binary_sensor.master_bath_timeout_threshold.state == 'on' }}
      - service: switch.turn_off
        entity_id: switch.master_bath_68

###################################################################################################################
## Master bath turn off if No motion OR KM Group Not Home, Humidity Threshold is below set value & No Motion for Set Value
###################################################################################################################

  - alias: Master Bath No Motion Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bath_esp_motion
        to: 'off'
        for: '00:01:00'
      - platform: state
        entity_id: group.km_status
        to: 'not_home'
    action:
      - wait_template: >-
          {{ states.binary_sensor.master_bath_below_threshold.state == 'on' }}
      - wait_template: >-
          {{ states.binary_sensor.master_bath_timeout_threshold.state == 'on' }}
      - service: switch.turn_off
        entity_id: switch.master_bath_68
###################################################################################################################
## Keep alive boolean sensor for calculations
###################################################################################################################

  - alias: Keep Alive
    initial_state: true
    hide_entity: true
    trigger:
      - platform: time
        seconds: '/1'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.keep_alive

###################################################################################################################
## Change motion to timeout to 5 mins after midnight OR KM not home
###################################################################################################################

  - id: change_master_bath_timeout_sleep
    initial_state: 'on'
    alias: Master Bath Change Timeout Sleep
    trigger:
      - platform: time
        at: '00:00:01'
      - platform: state
        entity_id: group.km_status
        to: 'not_home'
        for: '00:05:00'

    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.master_bath_timeout
        value: '5'

###################################################################################################################
## Change motion to timeout to 15 mins at 6AM
###################################################################################################################

  - id: change_master_bath_timeout_wakeup
    initial_state: 'on'
    alias: Master Bath Change Timeout Wake Up
    trigger:
      platform: time
      at: '06:00:00'

    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.master_bath_timeout
        value: '15'
